[Mysql]
# 数据库地址
Host = localhost
# 数据库端口
Port = 3306
# 数据库用户名
User = root
# 数据库密码
Password = 123456
# 数据库名
Database = cmyWebserver
# 数据库最大连接数
MaxConnections = 10
# 数据库连接标志
ClientFlags = 0
[ThreadPool]
# 线程池线程数量
ThreadNumber = 8
# 最大请求数
MaxRequests = 10000
[Log]
# 是否开启日志
LogEnable = 1
# 日志缓冲区大小
LogBufferSize = 8192
# 单个日志文件最大行数
LogSingleFileLine = 5000000
# 日志文件名
LogName = ServerLog
# 日志文件路径
LogPath = .
# 异步处理日志时的队列大小，0为同步处理
LogQueueSize = 1000
[Web]
# 延迟关闭连接的时间，超过则发送RST包强制关闭；0则不开启SO_LINGER
LingerTime = 1
# web服务器HTTP端口
Port = 80
# 监听触发模式，0为LT，1为ET
ListenTriggerMode = 0
# 连接触发模式，0为LT，1为ET
ConnectTriggerMode = 0
# web服务器工作模式，0为proactor，1为reactor
ActorModel = 0